service: products-api
frameworkVersion: "2"

provider:
  name: aws
  runtime: java11
  stage: dev
  region: us-east-2
  tracing:
    lambda: true
    apiGateway: true
  environment:
    PRODUCTS_TABLE_NAME:
      "Fn::ImportValue": "products-serverless-table-${self:provider.stage}"
    REGION: ${self:provider.region}
  iamRoleStatements:
    - ${file(../serverless.common.yml):lambdaPolicyXRay}
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/products-serverless-table-${self:provider.stage}"

package:
  artifact: 'target/products-rest-api-lambda-1.0-SNAPSHOT.jar'

functions:
  listProducts:
    handler: com.products.lambda.handler.ListProductsHandler
    events:
      - http:
          path: /products
          method: get
  getProduct:
    handler: com.products.lambda.handler.GetProductHandler
    events:
      - http:
          path: /products/{id}
          method: get
  createProduct:
    handler: com.products.lambda.handler.CreateProductHandler
    events:
      - http:
          path: /products
          method: post
  deleteProduct:
    handler: com.products.lambda.handler.DeleteProductHandler
    events:
      - http:
          path: /products/{id}
          method: delete